// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// get_survival_cpp_M1
double get_survival_cpp_M1(double RHO, double RAISE_KILLING, double LOWER_GROWTH, double DIAGNOSIS_THRESHOLD, double DEATH_THRESHOLD, double TREATMENT_DELAY, double TREATMENT_DURATION, double CHEMO_DELAY, double CHEMO_DURATION);
RcppExport SEXP _TumorImmuneModels_get_survival_cpp_M1(SEXP RHOSEXP, SEXP RAISE_KILLINGSEXP, SEXP LOWER_GROWTHSEXP, SEXP DIAGNOSIS_THRESHOLDSEXP, SEXP DEATH_THRESHOLDSEXP, SEXP TREATMENT_DELAYSEXP, SEXP TREATMENT_DURATIONSEXP, SEXP CHEMO_DELAYSEXP, SEXP CHEMO_DURATIONSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type RHO(RHOSEXP);
    Rcpp::traits::input_parameter< double >::type RAISE_KILLING(RAISE_KILLINGSEXP);
    Rcpp::traits::input_parameter< double >::type LOWER_GROWTH(LOWER_GROWTHSEXP);
    Rcpp::traits::input_parameter< double >::type DIAGNOSIS_THRESHOLD(DIAGNOSIS_THRESHOLDSEXP);
    Rcpp::traits::input_parameter< double >::type DEATH_THRESHOLD(DEATH_THRESHOLDSEXP);
    Rcpp::traits::input_parameter< double >::type TREATMENT_DELAY(TREATMENT_DELAYSEXP);
    Rcpp::traits::input_parameter< double >::type TREATMENT_DURATION(TREATMENT_DURATIONSEXP);
    Rcpp::traits::input_parameter< double >::type CHEMO_DELAY(CHEMO_DELAYSEXP);
    Rcpp::traits::input_parameter< double >::type CHEMO_DURATION(CHEMO_DURATIONSEXP);
    rcpp_result_gen = Rcpp::wrap(get_survival_cpp_M1(RHO, RAISE_KILLING, LOWER_GROWTH, DIAGNOSIS_THRESHOLD, DEATH_THRESHOLD, TREATMENT_DELAY, TREATMENT_DURATION, CHEMO_DELAY, CHEMO_DURATION));
    return rcpp_result_gen;
END_RCPP
}
// get_survival_cpp_M2
double get_survival_cpp_M2(double RHO, double RAISE_KILLING, double LOWER_GROWTH, double DIAGNOSIS_THRESHOLD, double DEATH_THRESHOLD, double TREATMENT_DELAY, double TREATMENT_DURATION, double CHEMO_DELAY, double CHEMO_DURATION);
RcppExport SEXP _TumorImmuneModels_get_survival_cpp_M2(SEXP RHOSEXP, SEXP RAISE_KILLINGSEXP, SEXP LOWER_GROWTHSEXP, SEXP DIAGNOSIS_THRESHOLDSEXP, SEXP DEATH_THRESHOLDSEXP, SEXP TREATMENT_DELAYSEXP, SEXP TREATMENT_DURATIONSEXP, SEXP CHEMO_DELAYSEXP, SEXP CHEMO_DURATIONSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type RHO(RHOSEXP);
    Rcpp::traits::input_parameter< double >::type RAISE_KILLING(RAISE_KILLINGSEXP);
    Rcpp::traits::input_parameter< double >::type LOWER_GROWTH(LOWER_GROWTHSEXP);
    Rcpp::traits::input_parameter< double >::type DIAGNOSIS_THRESHOLD(DIAGNOSIS_THRESHOLDSEXP);
    Rcpp::traits::input_parameter< double >::type DEATH_THRESHOLD(DEATH_THRESHOLDSEXP);
    Rcpp::traits::input_parameter< double >::type TREATMENT_DELAY(TREATMENT_DELAYSEXP);
    Rcpp::traits::input_parameter< double >::type TREATMENT_DURATION(TREATMENT_DURATIONSEXP);
    Rcpp::traits::input_parameter< double >::type CHEMO_DELAY(CHEMO_DELAYSEXP);
    Rcpp::traits::input_parameter< double >::type CHEMO_DURATION(CHEMO_DURATIONSEXP);
    rcpp_result_gen = Rcpp::wrap(get_survival_cpp_M2(RHO, RAISE_KILLING, LOWER_GROWTH, DIAGNOSIS_THRESHOLD, DEATH_THRESHOLD, TREATMENT_DELAY, TREATMENT_DURATION, CHEMO_DELAY, CHEMO_DURATION));
    return rcpp_result_gen;
END_RCPP
}
// get_survival_cpp_M3
double get_survival_cpp_M3(double RHO, double RAISE_KILLING, double LOWER_GROWTH, double DIAGNOSIS_THRESHOLD, double DEATH_THRESHOLD, double TREATMENT_DELAY, double TREATMENT_DURATION, double CHEMO_DELAY, double CHEMO_DURATION);
RcppExport SEXP _TumorImmuneModels_get_survival_cpp_M3(SEXP RHOSEXP, SEXP RAISE_KILLINGSEXP, SEXP LOWER_GROWTHSEXP, SEXP DIAGNOSIS_THRESHOLDSEXP, SEXP DEATH_THRESHOLDSEXP, SEXP TREATMENT_DELAYSEXP, SEXP TREATMENT_DURATIONSEXP, SEXP CHEMO_DELAYSEXP, SEXP CHEMO_DURATIONSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type RHO(RHOSEXP);
    Rcpp::traits::input_parameter< double >::type RAISE_KILLING(RAISE_KILLINGSEXP);
    Rcpp::traits::input_parameter< double >::type LOWER_GROWTH(LOWER_GROWTHSEXP);
    Rcpp::traits::input_parameter< double >::type DIAGNOSIS_THRESHOLD(DIAGNOSIS_THRESHOLDSEXP);
    Rcpp::traits::input_parameter< double >::type DEATH_THRESHOLD(DEATH_THRESHOLDSEXP);
    Rcpp::traits::input_parameter< double >::type TREATMENT_DELAY(TREATMENT_DELAYSEXP);
    Rcpp::traits::input_parameter< double >::type TREATMENT_DURATION(TREATMENT_DURATIONSEXP);
    Rcpp::traits::input_parameter< double >::type CHEMO_DELAY(CHEMO_DELAYSEXP);
    Rcpp::traits::input_parameter< double >::type CHEMO_DURATION(CHEMO_DURATIONSEXP);
    rcpp_result_gen = Rcpp::wrap(get_survival_cpp_M3(RHO, RAISE_KILLING, LOWER_GROWTH, DIAGNOSIS_THRESHOLD, DEATH_THRESHOLD, TREATMENT_DELAY, TREATMENT_DURATION, CHEMO_DELAY, CHEMO_DURATION));
    return rcpp_result_gen;
END_RCPP
}
// simulate_M1
NumericVector simulate_M1(double T_MAX, double RAISE_KILLING, double LOWER_GROWTH, double RHO, double DIAGNOSIS_THRESHOLD, double DEATH_THRESHOLD, double TREATMENT_DELAY, double TREATMENT_DURATION, double CHEMO_DELAY, double CHEMO_DURATION);
RcppExport SEXP _TumorImmuneModels_simulate_M1(SEXP T_MAXSEXP, SEXP RAISE_KILLINGSEXP, SEXP LOWER_GROWTHSEXP, SEXP RHOSEXP, SEXP DIAGNOSIS_THRESHOLDSEXP, SEXP DEATH_THRESHOLDSEXP, SEXP TREATMENT_DELAYSEXP, SEXP TREATMENT_DURATIONSEXP, SEXP CHEMO_DELAYSEXP, SEXP CHEMO_DURATIONSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type T_MAX(T_MAXSEXP);
    Rcpp::traits::input_parameter< double >::type RAISE_KILLING(RAISE_KILLINGSEXP);
    Rcpp::traits::input_parameter< double >::type LOWER_GROWTH(LOWER_GROWTHSEXP);
    Rcpp::traits::input_parameter< double >::type RHO(RHOSEXP);
    Rcpp::traits::input_parameter< double >::type DIAGNOSIS_THRESHOLD(DIAGNOSIS_THRESHOLDSEXP);
    Rcpp::traits::input_parameter< double >::type DEATH_THRESHOLD(DEATH_THRESHOLDSEXP);
    Rcpp::traits::input_parameter< double >::type TREATMENT_DELAY(TREATMENT_DELAYSEXP);
    Rcpp::traits::input_parameter< double >::type TREATMENT_DURATION(TREATMENT_DURATIONSEXP);
    Rcpp::traits::input_parameter< double >::type CHEMO_DELAY(CHEMO_DELAYSEXP);
    Rcpp::traits::input_parameter< double >::type CHEMO_DURATION(CHEMO_DURATIONSEXP);
    rcpp_result_gen = Rcpp::wrap(simulate_M1(T_MAX, RAISE_KILLING, LOWER_GROWTH, RHO, DIAGNOSIS_THRESHOLD, DEATH_THRESHOLD, TREATMENT_DELAY, TREATMENT_DURATION, CHEMO_DELAY, CHEMO_DURATION));
    return rcpp_result_gen;
END_RCPP
}
// simulate_M2
NumericVector simulate_M2(double T_MAX, double RAISE_KILLING, double LOWER_GROWTH, double RHO, double DIAGNOSIS_THRESHOLD, double DEATH_THRESHOLD, double TREATMENT_DELAY, double TREATMENT_DURATION, double CHEMO_DELAY, double CHEMO_DURATION);
RcppExport SEXP _TumorImmuneModels_simulate_M2(SEXP T_MAXSEXP, SEXP RAISE_KILLINGSEXP, SEXP LOWER_GROWTHSEXP, SEXP RHOSEXP, SEXP DIAGNOSIS_THRESHOLDSEXP, SEXP DEATH_THRESHOLDSEXP, SEXP TREATMENT_DELAYSEXP, SEXP TREATMENT_DURATIONSEXP, SEXP CHEMO_DELAYSEXP, SEXP CHEMO_DURATIONSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type T_MAX(T_MAXSEXP);
    Rcpp::traits::input_parameter< double >::type RAISE_KILLING(RAISE_KILLINGSEXP);
    Rcpp::traits::input_parameter< double >::type LOWER_GROWTH(LOWER_GROWTHSEXP);
    Rcpp::traits::input_parameter< double >::type RHO(RHOSEXP);
    Rcpp::traits::input_parameter< double >::type DIAGNOSIS_THRESHOLD(DIAGNOSIS_THRESHOLDSEXP);
    Rcpp::traits::input_parameter< double >::type DEATH_THRESHOLD(DEATH_THRESHOLDSEXP);
    Rcpp::traits::input_parameter< double >::type TREATMENT_DELAY(TREATMENT_DELAYSEXP);
    Rcpp::traits::input_parameter< double >::type TREATMENT_DURATION(TREATMENT_DURATIONSEXP);
    Rcpp::traits::input_parameter< double >::type CHEMO_DELAY(CHEMO_DELAYSEXP);
    Rcpp::traits::input_parameter< double >::type CHEMO_DURATION(CHEMO_DURATIONSEXP);
    rcpp_result_gen = Rcpp::wrap(simulate_M2(T_MAX, RAISE_KILLING, LOWER_GROWTH, RHO, DIAGNOSIS_THRESHOLD, DEATH_THRESHOLD, TREATMENT_DELAY, TREATMENT_DURATION, CHEMO_DELAY, CHEMO_DURATION));
    return rcpp_result_gen;
END_RCPP
}
// simulate_M3
NumericVector simulate_M3(double T_MAX, double RAISE_KILLING, double LOWER_GROWTH, double RHO, double DIAGNOSIS_THRESHOLD, double DEATH_THRESHOLD, double TREATMENT_DELAY, double TREATMENT_DURATION, double CHEMO_DELAY, double CHEMO_DURATION);
RcppExport SEXP _TumorImmuneModels_simulate_M3(SEXP T_MAXSEXP, SEXP RAISE_KILLINGSEXP, SEXP LOWER_GROWTHSEXP, SEXP RHOSEXP, SEXP DIAGNOSIS_THRESHOLDSEXP, SEXP DEATH_THRESHOLDSEXP, SEXP TREATMENT_DELAYSEXP, SEXP TREATMENT_DURATIONSEXP, SEXP CHEMO_DELAYSEXP, SEXP CHEMO_DURATIONSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type T_MAX(T_MAXSEXP);
    Rcpp::traits::input_parameter< double >::type RAISE_KILLING(RAISE_KILLINGSEXP);
    Rcpp::traits::input_parameter< double >::type LOWER_GROWTH(LOWER_GROWTHSEXP);
    Rcpp::traits::input_parameter< double >::type RHO(RHOSEXP);
    Rcpp::traits::input_parameter< double >::type DIAGNOSIS_THRESHOLD(DIAGNOSIS_THRESHOLDSEXP);
    Rcpp::traits::input_parameter< double >::type DEATH_THRESHOLD(DEATH_THRESHOLDSEXP);
    Rcpp::traits::input_parameter< double >::type TREATMENT_DELAY(TREATMENT_DELAYSEXP);
    Rcpp::traits::input_parameter< double >::type TREATMENT_DURATION(TREATMENT_DURATIONSEXP);
    Rcpp::traits::input_parameter< double >::type CHEMO_DELAY(CHEMO_DELAYSEXP);
    Rcpp::traits::input_parameter< double >::type CHEMO_DURATION(CHEMO_DURATIONSEXP);
    rcpp_result_gen = Rcpp::wrap(simulate_M3(T_MAX, RAISE_KILLING, LOWER_GROWTH, RHO, DIAGNOSIS_THRESHOLD, DEATH_THRESHOLD, TREATMENT_DELAY, TREATMENT_DURATION, CHEMO_DELAY, CHEMO_DURATION));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TumorImmuneModels_get_survival_cpp_M1", (DL_FUNC) &_TumorImmuneModels_get_survival_cpp_M1, 9},
    {"_TumorImmuneModels_get_survival_cpp_M2", (DL_FUNC) &_TumorImmuneModels_get_survival_cpp_M2, 9},
    {"_TumorImmuneModels_get_survival_cpp_M3", (DL_FUNC) &_TumorImmuneModels_get_survival_cpp_M3, 9},
    {"_TumorImmuneModels_simulate_M1", (DL_FUNC) &_TumorImmuneModels_simulate_M1, 10},
    {"_TumorImmuneModels_simulate_M2", (DL_FUNC) &_TumorImmuneModels_simulate_M2, 10},
    {"_TumorImmuneModels_simulate_M3", (DL_FUNC) &_TumorImmuneModels_simulate_M3, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_TumorImmuneModels(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
