# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Patient survival
#' 
#' Calculates survival of the patient in months with different models 
#'
#' @param RHO Tumor proliferation rate
#' @param RAISE_KILLING The multiplication factor to increase the killing rate 
#' of cytotoxic T cells as a treatment effect of immune therapy. The default 
#' value 1 indicates no treatment effect. To simulate the immune therapy effect
#' the value should be greater than 1.
#' @param LOWER_GROWTH The multiplication factor to reduce 
#' the tumor growth as a treatment effect of chemotherapy. The default 
#' value 1 indicates no treatment effect. To simulate the chemotherapy effect
#' the value should be lower than 1.
#' @param DIAGNOSIS_THRESHOLD The number of tumor cell at which cancer is diagnosed
#' @param DEATH_THRESHOLD The lethal number of tumor cell
#' @param TREATMENT_DELAY The delay between the diagnosis and start of 
#' the immune therapy in months
#' @param TREATMENT_DURATION Immune therapy duration in months
#' @param CHEMO_DELAY The delay between the diagnosis and start of 
#' the chemotherapy in months
#' @param CHEMO_DURATION Chemotherapy duration in months
#' @return The survival of a patient in months
#' @examples
#' # Model M1
#' # Get survival when no treatment is implemented using the default model parameters
#' survival <- get_survival_cpp_M1()
#' 
#' # Get survival when partial response to immune therapy is achieved 
#' # using the default model parameters
#' survival <- get_survival_cpp_M1(RAISE_KILLING=10)
#' 
#' # Get survival when complete response to immune therapy is achieved  
#' # using the default model parameters
#' survival <- get_survival_cpp_M1(RAISE_KILLING=15)
#' 
#' # Get survival when partial response to chemotherapy is achieved 
#' # using the default model parameters
#' survival <- get_survival_cpp_M1(LOWER_GROWTH=0.8)
#' 
#' # Get survival when complete response to chemotherapy is achieved  
#' # using the default model parameters
#' survival <- get_survival_cpp_M1(LOWER_GROWTH=0.19)
#' 
#' # Get survival when chemotherapy is followed by immune therapy  
#' # using the default model parameters
#' get_survival_cpp_M1(LOWER_GROWTH=0.5, CHEMO_DURATION=10, RAISE_KILLING=15, TREATMENT_DELAY=10, TREATMENT_DURATION=30)
#' 
#' # Model M2
#' # Get survival when no treatment is implemented using the default model parameters
#' survival <- get_survival_cpp_M2()
#' 
#' # Get survival when partial response to immune therapy is achieved 
#' # using the default model parameters
#' survival <- get_survival_cpp_M2(RAISE_KILLING=14000)
#' 
#' # Get survival when complete response to immune therapy is achieved  
#' # using the default model parameters
#' survival <- get_survival_cpp_M2(RAISE_KILLING=14500)
#' 
#' # Get survival when partial response to chemotherapy is achieved 
#' # using the default model parameters
#' survival <- get_survival_cpp_M2(LOWER_GROWTH_=0.5)
#' 
#' # Get survival when complete response to chemotherapy is achieved 
#' # using the default model parameters
#' survival <- get_survival_cpp_M2(LOWER_GROWTH_=0.01)
#' 
#' # Model M3
#' # Get survival when no treatment is implemented using the default model parameters
#' survival <- get_survival_cpp_M3()
#' 
#' # Get survival when partial response to immune therapy is achieved 
#' # using the default model parameters
#' survival <- get_survival_cpp_M3(RAISE_KILLING=10)
#' 
#' # Get survival when complete response to immune therapy is achieved  
#' # using the default model parameters
#' survival <- get_survival_cpp_M3(RAISE_KILLING=17)
#' 
#' # Get survival when partial response to chemotherapy is achieved 
#' # using the default model parameters
#' survival <- get_survival_cpp_M3(LOWER_GROWTH=0.8)
#' 
#' # Get survival when complete response to chemotherapy is achieved 
#' # using the default model parameters
#' survival <- get_survival_cpp_M3(LOWER_GROWTH=0.3)
get_survival_cpp_M1 <- function(RHO = 5.0, RAISE_KILLING = 1.0, LOWER_GROWTH = 1.0, DIAGNOSIS_THRESHOLD = 65e8, DEATH_THRESHOLD = 1e12, TREATMENT_DELAY = 0.0, TREATMENT_DURATION = 1e10, CHEMO_DELAY = 0.0, CHEMO_DURATION = 1e10) {
    .Call(`_TumorImmuneModels_get_survival_cpp_M1`, RHO, RAISE_KILLING, LOWER_GROWTH, DIAGNOSIS_THRESHOLD, DEATH_THRESHOLD, TREATMENT_DELAY, TREATMENT_DURATION, CHEMO_DELAY, CHEMO_DURATION)
}

get_survival_cpp_M2 <- function(RHO = 0.04495, RAISE_KILLING = 1.0, LOWER_GROWTH = 1.0, DIAGNOSIS_THRESHOLD = 65e8, DEATH_THRESHOLD = 1e12, TREATMENT_DELAY = 0.0, TREATMENT_DURATION = 1e10, CHEMO_DELAY = 0.0, CHEMO_DURATION = 1e10) {
    .Call(`_TumorImmuneModels_get_survival_cpp_M2`, RHO, RAISE_KILLING, LOWER_GROWTH, DIAGNOSIS_THRESHOLD, DEATH_THRESHOLD, TREATMENT_DELAY, TREATMENT_DURATION, CHEMO_DELAY, CHEMO_DURATION)
}

get_survival_cpp_M3 <- function(RHO = 0.04495, RAISE_KILLING = 1.0, LOWER_GROWTH = 1.0, DIAGNOSIS_THRESHOLD = 65e8, DEATH_THRESHOLD = 1e12, TREATMENT_DELAY = 0.0, TREATMENT_DURATION = 1e10, CHEMO_DELAY = 0.0, CHEMO_DURATION = 1e10) {
    .Call(`_TumorImmuneModels_get_survival_cpp_M3`, RHO, RAISE_KILLING, LOWER_GROWTH, DIAGNOSIS_THRESHOLD, DEATH_THRESHOLD, TREATMENT_DELAY, TREATMENT_DURATION, CHEMO_DELAY, CHEMO_DURATION)
}

#' Disease trajectory
#' 
#' Simulates the disease trajectory of a single patient with different models  
#'
#' @param T_MAX The maximum treatment duration in days
#' @param immuno_effect The multiplication factor to increase the killing rate 
#' of cytotoxic T cells as a treatment effect of immune therapy. The default 
#' value 1 indicates no treatment effect. To simulate the immune therapy effect
#' the value should be greater than 1.
#' @param chemo_effect param The multiplication factor to reduce 
#' the tumor growth as a treatment effect of chemotherapy. The default 
#' value 1 indicates no treatment effect. To simulate the chemotherapy effect
#' the value should be lower than 1.
#' 
#' @return A vector that represented the tumor growth under the implemented treatment. 
#' The vector consists of 3 concatenated vectors that represent 1) time scale, 
#' 2) tumor size at a given time, 3) number of intramural T cells at a given time.
#' Transform it to a matrix with the corresponding columns using matrix(x, ncol=3, byrow=TRUE)
#' to obtain the output in a format convenient for plotting.  
#' 
#' @examples
#' # Simulates the disease trajectory when no treatment is implemented
#' t_max <- 365 * 5 # five years
#' y <- simulate_M1(t_max, 1, 1)
#' y <- matrix(y, ncol=3, byrow=TRUE) # transform to extract time scale, tumor size and intramural T cells number
#' # Visualize the disease course in a period shortly before treatment and until death
#' tumor_size_start <- 1e8
#' t_start <- which.max(y[,2] >= 1e8) - 1
#' y <- y[-(1:t_start),]
#' tumor_size_death <- 1e12
#' y <- y[y[,2] <= tumor_size_death,] 
#' day_in_month <- 30.4
#' y[,1] <- (y[,1] - min(y[,1])) / 30.4
#' # Plot the millions of tumor cells by months 
#' plot( y[,1], y[,2]/1e6, log="y", type="l", col="orange", xlab="", ylab="tumor burden (million cells)")
simulate_M1 <- function(T_MAX = 120.0, RAISE_KILLING = 1.0, LOWER_GROWTH = 1.0, RHO = 5.0, DIAGNOSIS_THRESHOLD = 65e8, DEATH_THRESHOLD = 1e12, TREATMENT_DELAY = 0.0, TREATMENT_DURATION = 1e10, CHEMO_DELAY = 0.0, CHEMO_DURATION = 1e10) {
    .Call(`_TumorImmuneModels_simulate_M1`, T_MAX, RAISE_KILLING, LOWER_GROWTH, RHO, DIAGNOSIS_THRESHOLD, DEATH_THRESHOLD, TREATMENT_DELAY, TREATMENT_DURATION, CHEMO_DELAY, CHEMO_DURATION)
}

simulate_M2 <- function(T_MAX = 120.0, RAISE_KILLING = 1.0, LOWER_GROWTH = 1.0, RHO = 0.04495, DIAGNOSIS_THRESHOLD = 65e8, DEATH_THRESHOLD = 1e12, TREATMENT_DELAY = 0.0, TREATMENT_DURATION = 1e10, CHEMO_DELAY = 0.0, CHEMO_DURATION = 1e10) {
    .Call(`_TumorImmuneModels_simulate_M2`, T_MAX, RAISE_KILLING, LOWER_GROWTH, RHO, DIAGNOSIS_THRESHOLD, DEATH_THRESHOLD, TREATMENT_DELAY, TREATMENT_DURATION, CHEMO_DELAY, CHEMO_DURATION)
}

simulate_M3 <- function(T_MAX = 120.0, RAISE_KILLING = 1.0, LOWER_GROWTH = 1.0, RHO = 0.04495, DIAGNOSIS_THRESHOLD = 65e8, DEATH_THRESHOLD = 1e12, TREATMENT_DELAY = 0.0, TREATMENT_DURATION = 1e10, CHEMO_DELAY = 0.0, CHEMO_DURATION = 1e10) {
    .Call(`_TumorImmuneModels_simulate_M3`, T_MAX, RAISE_KILLING, LOWER_GROWTH, RHO, DIAGNOSIS_THRESHOLD, DEATH_THRESHOLD, TREATMENT_DELAY, TREATMENT_DURATION, CHEMO_DELAY, CHEMO_DURATION)
}

